#!/usr/bin/env bash
# Manages the manage_my_process script

case $1 in
	    start)
		            ./manage_my_process &
			            echo "$!" > /var/run/my_process.pid
				            echo "manage_my_process started"
					            ;;
						        stop)
								        [ -e "/var/run/my_process.pid" ] && pkill -f manage_my_process
									        rm -f /var/run/my_process.pid
										        echo "manage_my_process stopped"
											        ;;
												    restart)
													            $0 stop
														            $0 start
															            echo "manage_my_process restarted"
																            ;;
																	        *)
																			        echo "Usage: manage_my_process {start|stop|restart}"
																				        ;;
																			esac
